---
title: "Class 13"
author: "Ryan Chaney"
date: "2026-10-07"
output:  
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_download: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Plane Crash Example

<https://www.planecrashinfo.com/2025/2025.htm>
```{r}
year = 2025

crash_url = paste0('https://www.planecrashinfo.com/', year, '/', year, '.htm')

crash_page <- rvest::read_html(crash_url, encoding = "ISO-8859-1")

crash_page |> 
  rvest::html_elements("td:nth-child(1) > font > a") |>
  rvest::html_text2() -> dates

crash_page |> 
  rvest::html_elements("td:nth-child(1) > font > a") |>
  rvest::html_text2() -> loc

crash_page |> 
  rvest::html_elements("td:nth-child(1) > font") |>
  rvest::html_text2() -> fatalities

df = data.frame(dates = dates, loc = loc_op[-1], fatalities = fatalities[-1]) |>
  tidyr::separate(loc, into = ("location", "operator"), sep = "\n" ) |>
  tidyr::separate(loc, into = ("location", "operator"), sep = "\n" )


```

